package com.vibecode.companion.data.storage.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A named bundle of launch defaults the app restores when the launch screen opens.
 *
 * Today the app seeds and uses exactly one row (the "Default" profile, id
 * [com.vibecode.companion.data.storage.PreferenceProfileStore.DEFAULT_PROFILE_ID]); the
 * [id]/[name] columns and the autogenerated key exist so multiple named profiles can be added
 * later without a schema migration. Each field mirrors an in-memory launch option from
 * `LaunchUiState`: [defaultRepoUrl] and [defaultModelId] are nullable (no selection / server's
 * default model), and [defaultMode] holds the raw API mode string (see `data.api.AgentMode`).
 */
@Entity(tableName = "preference_profiles")
data class PreferenceProfileEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val defaultRepoUrl: String?,
    val defaultModelId: String?,
    val autoCreatePr: Boolean,
    val defaultMode: String,
)
